name = "danogo2023/bonds/issue-bond"
version = "1.0.0"
license = "Apache-2.0"
description = "Danogo Issue Bond"

[repository]
user = "danogo2023/bonds"
project = "issue-bond"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.7.0"
source = "github"

[[dependencies]]
name = "danogo2023/daken"
version = "v1.0.2"
source = "github"
