name = "danogo2023/bond-dex/limit-ask"
version = "3.0.1"
license = "Apache-2.0"
description = "Danogo Bond Exchanges: Ask Limit Optim Bond"

[repository]
user = "danogo2023/bond-dex"
project = "limit-ask"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.7.0"
source = "github"

[[dependencies]]
name = "danogo2023/daken"
version = "v1.1.0"
source = "github"
